
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
# specific path build
trigger:
  branches:
    include:
    - master
    - feature/*
    - bug/*
  paths:
    include:
    - api-layer/arm
    - api-layer/azure-pipelines/infra.deploy.yml

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: PublishArtefacts
  displayName: Publish Artefacts
  jobs:
  - job:
    displayName: Create ARM template artifact
    steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'api-layer/arm'
          Contents: '**'
          TargetFolder: $(Build.ArtifactStagingDirectory)
          CleanTargetFolder: true
          OverWrite: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifact: 'templates'
          publishLocation: 'pipeline'

- stage: CI
  displayName: Deploying to CI environment
  dependsOn: PublishArtefacts
  jobs:
  - deployment: 'DeployInfra'
    displayName: Deploying Infrastructure Resources
    environment: CI
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: templates
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'kk3157b'
              subscriptionId: 'bfae8067-8a34-4a4d-9a6b-2388a07e7b25'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'kk3157b'
              location: 'UK South'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/templates/azuredeploy.json'
              csmParametersFile: '$(Pipeline.Workspace)/templates/azuredeploy.parameters.dev.json'
              overrideParameters: '
              -repo $(Build.Repository.Name)
              '
              deploymentMode: 'Incremental'

- stage: Test
  displayName: Deploying to Test environment
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: CI
  jobs:
  - deployment: 'DeployInfraToTest'
    displayName: Deploying Infrastructure Resources to Test environment
    environment: Test
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: templates
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'kk3157b'
              subscriptionId: 'bfae8067-8a34-4a4d-9a6b-2388a07e7b25'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'kk3157b'
              location: 'UK South'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/templates/azuredeploy.json'
              csmParametersFile: '$(Pipeline.Workspace)/templates/azuredeploy.parameters.test.json'
              overrideParameters: '
              -repo $(Build.Repository.Name)
              '
              deploymentMode: 'Incremental'

- stage: Prod
  displayName: Deploying to Prod environment
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: Test
  jobs:
  - deployment: 'DeployInfraToProd'
    displayName: Deploying Infrastructure Resources to Prod environment
    environment: Prod
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: templates
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'kk3157b'
              subscriptionId: 'bfae8067-8a34-4a4d-9a6b-2388a07e7b25'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'kk3157b'
              location: 'UK South'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/templates/azuredeploy.json'
              csmParametersFile: '$(Pipeline.Workspace)/templates/azuredeploy.parameters.prod.json'
              overrideParameters: '
              -repo $(Build.Repository.Name)
              '
              deploymentMode: 'Incremental'